services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: disease-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app/Backend
      - ./Models_Files:/app/Models_Files
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: disease-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend