function SymptomDisplay() {
    return (
        <div className="symptoms max-h-80 overflow-y-auto border border-gray-200 rounded-lg p-4 shadow-inner">
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
            <p>gfdh</p>
        </div>
    )
}

export default SymptomDisplay